language: node_js
node_js:
- v8
- v10
- node
allow_failure:
  - node_js: v8

cache: npm

deploy:
  provider: npm
  email: hi@oncletom.io
  api-key: $NPM_TOKEN
  on:
    tags: true
    repo: oncletom/crx
